# .goreleaser.yml
project_name: kubic

before:
  hooks:
    - go mod tidy

builds:
  - env: [CGO_ENABLED=0]
    ldflags:
      - -s -w
      - -X main.buildDate={{.Date}}
      - -X main.gitVersion={{.Tag}}
      - -X main.gitHash={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    id: "kubic"
    dir: .
    main: .
    hooks:
      post: 'upx --best {{ .Path }}'

archives:
  - format: tar.gz
    replacements:
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

changelog:
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^refactor'
      - '^style'
      - '^test'